name: Deploy Examples

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout master
      run: |
        git pull origin master
        
    - name: NPM Restore
      working-directory: ./examples
      run: | 
        npm install
                       
    - name: Build
      working-directory: ./examples
      run: | 
        npm run build
        
    - name: Create folder and repo
      working-directory: ./examples
      run: |
        npm run io_create
        
    - name: Create Repository and Pull
      working-directory: ./examples/build/github-io
      run: | 
       git init
        git remote add production https://${{ secrets.PUBLIC_PAT }}@github.com/miscalencu/miscalencu.github.io.git
        git pull production master
        
    - name: Copy/Overwrite Build
      working-directory: ./examples
      run: | 
        npm run io_copy
        
    - name: Commit and Publish
      working-directory: ./examples/build/github-io
      run: |
        git add -all
        git commit -m:"Deploy /Npm-React-Digital-Grid/Examples"
        git config --global user.email "george.miscalencu@gmail.com"
        git config --global user.name "miscalencu"
        git push production master
