name: Deploy Examples

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout master
      run: |
        git fetch origin
        
    - name: Build
      working-directory: ./examples
      run: | 
        npm run build
        
    - name: Publish
      working-directory: ./examples/build
      run: |
        npm git remote add production https://github.com/miscalencu/miscalencu.github.io.git
        
