name: Deploy Examples

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#      with: 
#        github_token: ${{secrets.PAT}}

    - name: Checkout master
      run: |
        git pull origin
        
    - name: NPM Restore
      working-directory: ./examples
      run: | 
        npm install
                       
    - name: Build
      working-directory: ./examples
      run: | 
        npm run build
        
    - name: Publish
      working-directory: ./examples/build
      run: |
        git remote add production https://miscalencu:${{secrets.PUBLIC_PAT}}@github.com/miscalencu/miscalencu.github.io.git
        git push --force production master
        
