name: Deploy Examples

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout master
      run: |
        git fetch origin
    - name: Build
      run: |
        cd /examples/
        npm run build
